config/routes.rb
Rails.application.routes.draw do
  devise_for :user, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', passwords: 'users/passwords' }

  get 'p/:page', to: 'pages#show', as: :page
  root to: 'pages#show', page: 'ganhador'
  resources :coupons, only: [:index] do
    post 'sync', on: :collection
  end
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :order, optional: true
  validates :number, :series, :uuid, presence: true
  validates :number, uniqueness: { scope: :series }

  before_validation :generate_uuid, on: :create
  before_save :block_removal, on: :update
  scope :unused, -> { where(user_id: nil, order_id: nil) }
  scope :random_pick, -> (amount) { order("RANDOM()").first(amount) }

  private

  def generate_uuid
    self.uuid ||= SecureRandom.uuid
  end

  def block_removal
    if user_id_was.is_a?(Integer) && changes.include?("user_id")
      raise CouponRemovalNotAllowed
    end

    if order_id_was.is_a?(Integer) && changes.include?("order_id")
      raise CouponRemovalNotAllowed
    end
  end
end

class CouponRemovalNotAllowed < Exception
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  respond_to :html, :js
  before_action :authenticate_user!

  def index
    @coupons = Coupon.where(user: current_user)
  end

  def sync
    begin
      syncr = CouponSyncService.new(current_user)
      syncr.compare_orders

      if syncr.sync
        flash[:success] = I18n.t(:sync_successful)
        CouponMailer.coupon_associated(current_user).deliver_later
      else
        flash[:alert] = I18n.t(:empty_order_list)
      end

      @coupons = current_user.coupons.reload

      respond_with @coupons, location: coupons_url
    rescue NoCouponsException => e
      redirect_to coupons_path, alert: I18n.t(:no_more_coupons)
    end
  end
end

app/helpers/coupons_helper.rb
module CouponsHelper
  def format_coupon(coupon)
    [format_coupon_series(coupon), format_coupon_number(coupon)].join('/')
  end

  def format_coupon_series(coupon)
    coupon.series.to_s.rjust(2, '0')
  end

  def format_coupon_number(coupon)
    coupon.number.to_s.rjust(5, '0')
  end
end

app/views/coupons/_coupon_deck.html.erb
<% coupons.each do |coupon| %>
  <div class="card coupon">
    <%= content_tag :div, class: "card-img-top bg-#{coupon.series == 0 ? 'warning' : 'success'}" do %>
      <div class="coupon-number pt-2 pb-2 text-center">
        <div class="series mb-1 text-white">
          <%= icon('ticket-alt tilted') %>
          <strong> Série: <%= format_coupon_series(coupon) %></strong>
        </div>
        <%== format_coupon_number(coupon).split('').map { |digit| content_tag :span, digit }.join %>
      </div>
    <% end %>
    <div class="card-body">
      <p class="card-text">
      <dl>
        <dt><%= t :order_number %></dt>
        <dd><%= coupon.order.number %></dd>

        <dt><%= t :associated_at %></dt>
        <dd> <%= l coupon.order.created_at, format: :short %> </dd>
      </dl>
      </p>
    </div>
  </div>
<% end %>

app/views/coupons/_svg.html.erb
<svg class="bd-placeholder-img card-img-top" width="100%" height="80" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Image cap"><title>Placeholder</title><rect fill="#ff85d5" width="100%" height="100%"></rect><text fill="white" dy=".3em" x="50%" y="50%">
<%= content %>
</text></svg>

app/views/coupons/index.html.erb
<div class="row mt-5">
  <div class="col-md-4 col-sm-12">
    <%= content_tag :h1, t(:my_coupons) %>
    <%= link_to icon_text('ticket-alt', t(:sync_coupons)), sync_coupons_path, class: 'btn btn-primary', method: :post %>
  </div>
  <div class="col-md-8 col-sm-12">
    <%= content_tag :p, t(:introduction), class: 'text-white text-right mr-5 h6 introduction-text' %>
  </div>
  <div class="col-md-12 pt-5">
    <% if current_user.coupons.empty?%>
      <div class="row">
        <div class="col-md-6 mx-auto">
          <p class="text-center alert alert-info">
          <%== t :no_coupons_yet, link: link_to(['','aqui',''].join('&nbsp;').html_safe, sync_coupons_path, method: :post, class: 'text-info') %>
          </p>
        </div>
      </div>
    <% end %>
    <div class="card-columns" data-wrapper='coupons'>
      <%= render 'coupon_deck', coupons: current_user.coupons %>
    </div>
  </div>
</div>

app/views/coupons/sync.js.erb
document.addEventListener("turbolinks:load", function() {
  console.log('BLALABLALAL')
  $('[data-wrapper=coupons]').smoothReplace("<%= j render 'coupon_deck', coupons: @coupons %>")
})