config/routes.rb
Rails.application.routes.draw do
  devise_for :user, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', passwords: 'users/passwords' }

  get 'p/:page', to: 'pages#show', as: :page
  root to: 'pages#show', page: 'ganhador'
  resources :coupons, only: [:index] do
    post 'sync', on: :collection
  end
end

app/views/shared/_city_shadow.html.erb
<div class="city-image-wrapper">
  <div class="shadow">
    <%= image_tag asset_pack_path('static/cidade.png') %>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="logo">
  <%= image_tag asset_pack_path('static/logo_pre.png'), class: 'logo-pre' %>
  <%= image_tag asset_pack_path('static/logo_klasme.png'), class: 'logo-klasme' %>
  <%= image_tag asset_pack_path('static/logo_plus.png'), class: 'logo-plus' %>
  <%= image_tag asset_pack_path('static/logo_niina.png'), class: 'logo-niina' %>
</div>
<div class="container">
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %> float-alert">
      <%= value %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>
<% if current_user %>
  <nav class="navbar navbar-expand-lg mx-auto navbar-custom">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto">
        <li class="nav-item">
          <%= link_to icon_text('ticket-alt', t(:my_coupons)), root_path, class: "nav-link #{ 'active' if current_page?(root_path) || current_page?(coupons_path) }" %>
        </li>
        <li class="nav-item">
          <%= link_to icon_text('file-alt', t(:terms)), page_path(:regulamento), class: "nav-link #{ 'active' if current_page?(page_path(:regulamento)) }"  %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= icon('user') %> Minha Conta
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item disabled" disabled aria-disabled='true'>
              <small>CPF: <%= format_cpf(current_user) %></small><br>
              <small>E-mail: <%= current_user.email %></small><br>
              <small>Nome: <%= full_name(current_user) %></small><br>
            </a>
            <div class="dropdown-divider"></div>
            <%= link_to icon_text('edit', t(:edit_your_account)), edit_user_registration_path, class: 'dropdown-item' %>
            <%= link_to icon_text('power-off', t(:logout)), destroy_user_session_path, class: 'dropdown-item', method: :delete %>
          </div>
        </li>
      </ul>
    </div>
  </nav>
<% end %>